### ISSUE TITLE
Forgot to mention how to start the bot 

### ISSUE THREAD

**Issue by Charlie1093** [tungdo0602/Myuu-Grinder#1]
I am stuck here, 
![image](https://github.com/tungdo0602/Myuu-Grinder/assets/77564709/503fdaaf-bd27-4c0f-a981-f12a85e64c86)

**Comment by tungdo0602** [comment]
yeah that's mean the bot is working now

**Comment by tungdo0602** [comment]
now you just need to use `.help` to list all command that bot support. Also recommend to use the bot in private server that you made

**Comment by Charlie1093** [comment]
Yes i am using a private server but it dosent let me type anything in that cmd prompt

**Comment by Charlie1093** [comment]
can i get ur discord so i can contact u better?

**Comment by tungdo0602** [comment]
> can i get ur discord so i can contact u better?

tungvn

**Comment by tungdo0602** [comment]
that is my username
